config/routes.rb
Rails.application.routes.draw do
  resources :gardens, only: [:index, :show] do
    resources :plants, only: [:new, :create]
  end

  resources :plants, only: :destroy do
    # /plants/:plant_id/plant_tags/new
    resources :plant_tags, only: [:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants, dependent: :destroy
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
  has_many :plant_tags
  has_many :tags, through: :plant_tags

  validates :name, presence: true, uniqueness: true
  validates :banner_url, presence: true
end

app/models/plant_tag.rb
class PlantTag < ApplicationRecord
  belongs_to :tag
  belongs_to :plant

  validates :plant_id, uniqueness: { scope: :tag_id }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :plant_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: :show

  # GET /gardens
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1
  def show
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_garden
    @garden = Garden.find(params[:id])
  end
end

app/controllers/plant_tags_controller.rb
class PlantTagsController < ApplicationController
  def new
    @plant_tag = PlantTag.new
    @plant = Plant.find(params[:plant_id])
  end

  def create
    # 1. initiate an instance of plant tag with data form the form
    @plant_tag = PlantTag.new(plant_tag_params)

    # 2. find the plant
    @plant = Plant.find(params[:plant_id])

    # 3. connect the plant and the plant tag
    @plant_tag.plant = @plant

    # 4. we save the plant tag
    if @plant_tag.save
      redirect_to @plant.garden
    else
      render :new
    end
  end

  private

  def plant_tag_params
    params.require(:plant_tag).permit(:tag_id)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

  def new
    @plant = Plant.new
    @garden = Garden.find(params[:garden_id])
  end

  def create
    @plant = Plant.new(plant_params)
    @garden = Garden.find(params[:garden_id])

    @plant.garden = @garden

    if @plant.save
      redirect_to @garden
    else
      render :new
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    redirect_to @plant.garden
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :banner_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plant_tags_helper.rb
module PlantTagsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/_form.html.erb
<%= simple_form_for(@garden) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :banner_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/gardens/edit.html.erb
<h1>Editing Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Show', @garden %> |
<%= link_to 'Back', gardens_path %>

app/views/gardens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gardens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Banner url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gardens.each do |garden| %>
      <tr>
        <td><%= garden.name %></td>
        <td><%= garden.banner_url %></td>
        <td><%= link_to 'Show', garden %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/gardens/new.html.erb
<h1>New Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Back', gardens_path %>

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @garden.banner_url %>);">

  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>

</div>

<div class="container">
  <%= link_to new_garden_plant_path(@garden), class: 'btn btn-primary my-3' do %>
    <i class="fas fa-seedling"></i>
  <% end %>



  <div class="cards">
    <% @garden.plants.each do |plant| %>
    <div class="card-category position-relative" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= plant.banner_url %>)">
      <%= plant.name %>

      <%= link_to 'delete',
                  plant_path(plant),
                  method: :delete,
                  class: 'btn btn-danger position-absolute eraser',
                  data: { confirm: 'Are you sure ?'}
      %>

      <div class="card-tags">
        <% plant.tags.each do |tag| %>
          <span><%= tag.name %></span>
        <% end %>

        <%= link_to '+', new_plant_plant_tag_path(plant) %>
      </div>

    </div>
    <% end %>
  </div>

</div>
<%= link_to 'Back', gardens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardensAndPlants714</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plant_tags/new.html.erb
<%= simple_form_for([@plant, @plant_tag]) do |f| %>
  <%= f.association :tag %>
  <%= f.button :submit, class: 'btn btn-success' %>
<% end %>

app/views/plants/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-7">
      <%= simple_form_for([@garden, @plant]) do |f| %>
        <%= f.input :name %>
        <%= f.input :banner_url %>

        <%= f.button :submit, class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>